---
version: "2.1"

services:
  meerkat:
    build:
      dockerfile: Dockerfile
      context: ./packages/meerkat
    environment:
      - KAFKA_VERSION=2.2.0
      - LOG_TAG_SERVICE=meerkat
      - ENVIRONMENT=DEVELOPMENT
      - APP_URL=http://localhost:8021
      - MONGO_HOST=skel_db
      - MONGO_PORT=27017
      - MONGO_DB=meerkat
    ports:
      - "8000:8000"
    depends_on:
      - skel_zookeeper
      - skel_kafka
      - skel_es
      - skel_db
    entrypoint:
      - sh
      - .docker/entrypoint.sh
    volumes:
      - ./:/code
      - /code/packages/meerkat/.venv
    links:
      - skel_zookeeper
      - skel_kafka
      - skel_es
      - skel_db

  nginx:
    build:
      context: ./.docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.template
      - ./.docker/logs/nginx:/var/log/nginx:cached
    ports:
      - "8021:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PROXY_HOST=meerkat
      - PROXY_PORT=8000
    depends_on:
      - meerkat
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  skel_db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - .data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  skel_es:
    build:
      context: ./.docker/es
      dockerfile: Dockerfile
    command: elasticsearch
    container_name: skel_es
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:9200/_cluster/health || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_local=true
      - cluster.name=talks-cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - skel_es:/usr/share/elasticsearch/data


volumes:
  skel_grafana_vol:
  skel_graf_db:
  skel_es:
  prom_data: {}
